<?php

$title = 'Add new pessoa';
$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php
// This provides a default CSS class and placeholder text for the title element:
    $pessoa = $form->get('name');
    $pessoa->setAttribute('class', 'form-control');
    $pessoa->setAttribute('placeholder', 'Name');
    
    // This provides a default CSS class and placeholder text for the artist element:
    $lastname = $form->get('lastname');
    $lastname->setAttribute('class', 'form-control');
    $lastname->setAttribute('placeholder', 'Last Name');

    $email = $form->get('email');
    $email->setAttribute('class', 'form-control');
    $email->setAttribute('placeholder', 'Email');

    $status = $form->get('status');
    $status->setAttribute('class', 'form-control');
    $status->setAttribute('placeholder', 'Status');

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');
    
    $form->setAttribute('action', $this->url('pessoa', ['action' => 'add']));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    <?php // Wrap the elements in divs marked as form groups, and render the
          // label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($pessoa) ?>
        <?= $this->formElement($pessoa) ?>
        <?= $this->formElementErrors()->render($pessoa, ['class' => 'help-block']) ?>
    </div>
    
    <div class="form-group">
        <?= $this->formLabel($lastname) ?>
        <?= $this->formElement($lastname) ?>
        <?= $this->formElementErrors()->render($lastname, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>
    
    <div class="form-group">
        <?= $this->formLabel($status) ?>
        <?= $this->formElement($status) ?>
        <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
    </div>

    <?php
    echo $this->formSubmit($submit);
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();