<?php

$title = 'Edit pessoa';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php

$pessoa = $form->get('name');
$pessoa->setAttribute('class', 'form-control');
$pessoa->setAttribute('placeholder', 'pessoa name');

$lastname = $form->get('lastname');
$lastname->setAttribute('class', 'form-control');
$lastname->setAttribute('placeholder', 'lastname');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'email');

$status = $form->get('status');
$status->setAttribute('class', 'form-control');
$status->setAttribute('placeholder', 'status');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('pessoa', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($pessoa) ?>
    <?= $this->formElement($pessoa) ?>
    <?= $this->formElementErrors()->render($pessoa, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($lastname) ?>
    <?= $this->formElement($lastname) ?>
    <?= $this->formElementErrors()->render($lastname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($status) ?>
    <?= $this->formElement($status) ?>
    <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();