<?php
    $title = 'Pessoas';
    $this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('pessoa', ['action' => 'add']) ?>">Add new pessoa</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Last Name</th>
    <th>Email</th>    
    <th>Status</th>    
    <th>&nbsp;</th>
</tr>
<?php foreach ($pessoas as $pessoa) : ?>
    <tr>
        <td><?= $this->escapeHtml($pessoa->getName()) ?></td>
        <td><?= $this->escapeHtml($pessoa->getLastName()) ?></td>
        <td><?= $this->escapeHtml($pessoa->getEmail()) ?></td>
        <td><?= $this->escapeHtml($pessoa->getStatus()) ?></td>
        <td>
            <a href="<?= $this->url('pessoa', ['action' => 'edit', 'id' => $pessoa->getId()]) ?>">Edit</a>
            <a href="<?= $this->url('pessoa', ['action' => 'delete', 'id' => $pessoa->getId()]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>